export LC_LANG=ru_RU.UTF-8
export QT_QPA_PLATFORMTHEME=qt5ct

set -m

atexit() {
  kill -TERM -- -$$ $(printf "-%s " $(jobs -p))
}

trap 'atexit' EXIT

ulimit -Sc 0

xset b off

. ~/.profile

xrdb -merge ~/.Xresources
autocutsel &

# --no-dock-shadow 
#picom --backend glx --vsync --glx-no-stencil --glx-no-rebind-pixmap --detect-client-opacity --detect-rounded-corners -I 0.04 -O 0.04 -c -f -b
# picom --use-ewmh-active-win --shadow-exclude '!focused' --detect-rounded-corners --backend xrender --vsync  -I 0.04 -O 0.04 -c -f -b
picom --no-use-damage --force-win-blend -b

xrandr --dpi 96

exec ck-launch-session mate-session
